name: Rengine CI

on:
  push:
    branches:
      - migration
  pull_request:
    branches:
      - migration

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, archlinux]
        compiler: [gcc, llvm, msvc]
        exclude:
          - os: windows-latest
            compiler: llvm
          - os: archlinux
            compiler: msvc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (Arch Linux)
        if: matrix.os == 'archlinux'
        run: sudo pacman -Syu --noconfirm cmake gcc clang

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install cmake gcc

      - name: Configure CMake
        run: cmake -B build -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}

      - name: Build project
        run: cmake --build build
